env:
  commonjs: true
  es6: true
  node: true

plugins:
  - '@typescript-eslint'

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: latest

ignorePatterns:
  - dist
  - build.js

rules:
  # Turn off rules
  '@typescript-eslint/no-empty': off
  '@typescript-eslint/no-var-requires': off
  '@typescript-eslint/no-namespace': off

  # Set some rules from error to warining
  '@typescript-eslint/no-empty-function': warn
  '@typescript-eslint/no-unused-vars': warn
  prefer-const: warn

  # Coding styles
  indent: [warn, 2, { SwitchCase: 1 }]
  semi: [warn, never]
  quotes: [warn, single]
  comma-dangle: [warn, always-multiline]