env:
  commonjs: true
  es6: true
  node: true

plugins:
  - '@typescript-eslint'

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 12
  sourceType: module

ignorePatterns:
  - dist
  - build.js

rules:
  '@typescript-eslint/no-namespace': [off]
  comma-dangle: [warn, always-multiline]
  indent: [warn, 2, { SwitchCase: 1 }]
  no-empty: [warn]
  no-unused-vars: [warn]
  prefer-const: [warn]
  quotes: [warn, single]
  semi: [warn, never]
