env:
  browser: true
  node: true
  es2021: true

plugins:
  - react
  - '@typescript-eslint'

extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 12
  sourceType: module

rules:
  no-unused-vars: [warn]
  no-empty: [warn]
  prefer-const: [warn]

  semi: [warn, never]
  quotes: [warn, single]
  comma-dangle: [warn, never]
  indent: [warn, 2, { SwitchCase: 1 }]